package com.syriabazaar.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CarModelAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarModelAllPropertiesEquals(CarModel expected, CarModel actual) {
        assertCarModelAutoGeneratedPropertiesEquals(expected, actual);
        assertCarModelAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarModelAllUpdatablePropertiesEquals(CarModel expected, CarModel actual) {
        assertCarModelUpdatableFieldsEquals(expected, actual);
        assertCarModelUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarModelAutoGeneratedPropertiesEquals(CarModel expected, CarModel actual) {
        assertThat(actual)
            .as("Verify CarModel auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarModelUpdatableFieldsEquals(CarModel expected, CarModel actual) {
        assertThat(actual)
            .as("Verify CarModel relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarModelUpdatableRelationshipsEquals(CarModel expected, CarModel actual) {
        assertThat(actual)
            .as("Verify CarModel relationships")
            .satisfies(a -> assertThat(a.getBrand()).as("check brand").isEqualTo(expected.getBrand()));
    }
}
