package com.syriabazaar.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CarTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarTypeAllPropertiesEquals(CarType expected, CarType actual) {
        assertCarTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertCarTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarTypeAllUpdatablePropertiesEquals(CarType expected, CarType actual) {
        assertCarTypeUpdatableFieldsEquals(expected, actual);
        assertCarTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarTypeAutoGeneratedPropertiesEquals(CarType expected, CarType actual) {
        assertThat(actual)
            .as("Verify CarType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarTypeUpdatableFieldsEquals(CarType expected, CarType actual) {
        assertThat(actual)
            .as("Verify CarType relevant properties")
            .satisfies(a -> assertThat(a.getTypeName()).as("check typeName").isEqualTo(expected.getTypeName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarTypeUpdatableRelationshipsEquals(CarType expected, CarType actual) {
        // empty method
    }
}
