package com.syriabazaar.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityAllPropertiesEquals(City expected, City actual) {
        assertCityAutoGeneratedPropertiesEquals(expected, actual);
        assertCityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityAllUpdatablePropertiesEquals(City expected, City actual) {
        assertCityUpdatableFieldsEquals(expected, actual);
        assertCityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityAutoGeneratedPropertiesEquals(City expected, City actual) {
        assertThat(actual)
            .as("Verify City auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityUpdatableFieldsEquals(City expected, City actual) {
        assertThat(actual)
            .as("Verify City relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityUpdatableRelationshipsEquals(City expected, City actual) {
        // empty method
    }
}
