package com.syriabazaar.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SellerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSellerAllPropertiesEquals(Seller expected, Seller actual) {
        assertSellerAutoGeneratedPropertiesEquals(expected, actual);
        assertSellerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSellerAllUpdatablePropertiesEquals(Seller expected, Seller actual) {
        assertSellerUpdatableFieldsEquals(expected, actual);
        assertSellerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSellerAutoGeneratedPropertiesEquals(Seller expected, Seller actual) {
        assertThat(actual)
            .as("Verify Seller auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSellerUpdatableFieldsEquals(Seller expected, Seller actual) {
        assertThat(actual)
            .as("Verify Seller relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a -> assertThat(a.getMobileNo()).as("check mobileNo").isEqualTo(expected.getMobileNo()))
            .satisfies(a -> assertThat(a.getWhatsApp()).as("check whatsApp").isEqualTo(expected.getWhatsApp()))
            .satisfies(a -> assertThat(a.getFacebook()).as("check facebook").isEqualTo(expected.getFacebook()))
            .satisfies(a -> assertThat(a.getInsta()).as("check insta").isEqualTo(expected.getInsta()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSellerUpdatableRelationshipsEquals(Seller expected, Seller actual) {
        // empty method
    }
}
